name: Generate Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'   # once a day
  workflow_dispatch:        # allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          user: YoussefJarray
          theme: tokyonight
          template: profile-details, repos-per-language, stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
